server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

keycloak:
  jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI}
  token-uri: ${KEYCLOAK_TOKEN_URI}
  userinfo-uri: ${KEYCLOAK_USERINFO_URI}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  secret: ${KEYCLOAK_SECRET}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

config:
  server:
    url: ${CONFIG_SERVER_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
